In [66]:
import pandas as pd
df = pd.read_csv("./dataset/work6.csv")
df

                              text
0            อาหารหวานมาก ไม่อร่อย
1  กินอาหารอร่อยมาก หวานดี อร่อยดี
2              อาหารอร่อยดีไม่หวาน

In [67]:
import nltk
from pythainlp.corpus.common import thai_stopwords
from pythainlp.tokenize import word_tokenize
import re
import string
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /home/night/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [68]:
import pythainlp
from pythainlp.util import emoji_to_thai


#function for removing number
def remove_numbers(text):
    number_pattern = r'\d+'
    without_number = re.sub(pattern=number_pattern, repl=" ", string=text)
    return without_number

#function for removing punctuation
def remove_punctuation(text):
    return text.translate(str.maketrans('', '', string.punctuation))

#function for removing stopword
def remove_stopwords(text):
    removed = []
    #stop_words = list(stopwords.words("english"))
    stopwords = list(thai_stopwords())
    tokens = word_tokenize(text)
    for i in range(len(tokens)):
        if tokens[i] not in stopwords:
            removed.append(tokens[i])
    return "".join(removed)

def tokenization_thai(text):
    token = word_tokenize(text,engine='longest', keep_whitespace=False)
    return " ".join(token)


#function for removing extra white_spaces
def remove_extra_white_spaces(text):
    space_pattern = r'\s+'
    without_sc = re.sub(pattern=space_pattern, repl="", string=text)
    return without_sc

In [69]:
df['text'] = df['text'].apply(lambda x: remove_numbers(x)) #remove number
df['text'] = df['text'].apply(lambda x: remove_punctuation(x)) #remove punc
df['text'] = df['text'].apply(lambda x: remove_stopwords(x)) #remove stopword

df['text'] = df['text'].apply(lambda x: tokenization_thai(x)) #Lemmatization
df['text'] = df['text'].apply(lambda x: remove_extra_white_spaces(x)) #remove white space
df.head()

                         text
0              อาหารหวานอร่อย
1  กินอาหารอร่อยหวานดีอร่อยดี
2            อาหารอร่อยดีหวาน

# onehot

In [70]:
vocab = set()
for text in df['text']:
    tokens = word_tokenize(text)
    for token in tokens:
        vocab.add(token)
vocab = list(vocab)
vocab

['ดี', 'อาหาร', 'อร่อย', 'หวาน', 'กิน', 'อาหารหวาน']

In [71]:
#create one hot vector of dataset
import numpy as np

# Create a dictionary to map words to integers
word_to_int = {word: i for i, word in enumerate(vocab)}
print(word_to_int)

# Create a binary vector for each word in each sentence
one_hot_vectors = []
for sentence in df['text']:
    words = word_tokenize(sentence)
    sentence_vectors = []
    for word in words:
        binary_vector = np.zeros(len(vocab)) #ให้ vector เป็น 0 หมดก่อน [0,0,0,0]
        binary_vector[word_to_int[word]] = 1 #first [0,0,1,0]
        sentence_vectors.append(binary_vector)
    one_hot_vectors.append(sentence_vectors)

one_hot_vectors

{'ดี': 0, 'อาหาร': 1, 'อร่อย': 2, 'หวาน': 3, 'กิน': 4, 'อาหารหวาน': 5}

[[array([0., 0., 0., 0., 0., 1.]), array([0., 0., 1., 0., 0., 0.])],
 [array([0., 0., 0., 0., 1., 0.]),
  array([0., 1., 0., 0., 0., 0.]),
  array([0., 0., 1., 0., 0., 0.]),
  array([0., 0., 0., 1., 0., 0.]),
  array([1., 0., 0., 0., 0., 0.]),
  array([0., 0., 1., 0., 0., 0.]),
  array([1., 0., 0., 0., 0., 0.])],
 [array([0., 1., 0., 0., 0., 0.]),
  array([0., 0., 1., 0., 0., 0.]),
  array([1., 0., 0., 0., 0., 0.]),
  array([0., 0., 0., 1., 0., 0.])]]

In [72]:
#find max len of documents for padding
max_sent = max(one_hot_vectors , key = len)
max_sent_length = len(max_sent)
max_sent_length

7

In [73]:
#pad = post to the same size for all documents
dimension = len(vocab)
pad = np.zeros(shape=(1, dimension)) #[0,0,0,0]
X=[]
for x in one_hot_vectors:
  if len(x)<max_sent_length:
    dif_len = max_sent_length-len(x)
    for i in range(0,dif_len):
      x = np.concatenate([x, pad])
  X.append(x)
X = np.array(X)
print(X)
print(X.shape)

[[[0. 0. 0. 0. 0. 1.]
  [0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 1. 0.]
  [0. 1. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0.]
  [1. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0.]]

 [[0. 1. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]
(3, 7, 6)

# wordEmbedding

In [ ]:
doc_tokens = [] 
for text in df['text']:
    tokens = word_tokenize(text)
    doc_tokens.append(tokens)

doc_tokens

[['อาหารหวาน', 'อร่อย'],
 ['กิน', 'อาหาร', 'อร่อย', 'หวาน', 'ดี', 'อร่อย', 'ดี'],
 ['อาหาร', 'อร่อย', 'ดี', 'หวาน']]

In [75]:
# without pretrained model, train model from your dataset
from pythainlp import word_vector

# train model
#important parameters
# vector_size: (default 100) The number of dimensions of the embedding
# sg: (default 0 or CBOW) The training algorithm, either CBOW (0) or skip gram (1).
# min_count: (default 5) The minimum count of words to consider when training the model; words with an occurrence less than this count will be ignored.



dimension = 10 #define number of dimension of word embeding vector
model = word_vector.WordVector(model_name="thai2fit_wv").get_model()

Corpus: thai2fit_wv
- Downloading: thai2fit_wv 0.1

/home/night/Git_Hub/-natural-language-processing/venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
100%|██████████| 62452646/62452646 [00:05<00:00, 12079662.10it/s]

In [76]:
def word_vectors(text, word_dict=model.index_to_key):
  tokens = word_tokenize(text)

  vectors = []

  for token in tokens:
    if token not in word_dict:
      continue
    token_vector = model[token]
    vectors.append(token_vector)
  return vectors

In [77]:
# load model that was created from your dataset
text ="หวาน"
embed_vector = word_vectors(text)
print(embed_vector)

[array([ 1.59253e-01,  6.43510e-02, -1.76604e-01, -1.21169e-01,
       -6.12690e-02, -3.63560e-02, -3.05810e-02, -2.06242e-01,
       -1.73866e-01, -1.41345e-01, -1.41503e-01, -1.75380e-02,
       -4.11740e-02,  5.81800e-03,  5.09390e-02,  2.70040e-02,
       -1.15591e-01,  5.46000e-03, -1.85452e-01, -9.02610e-02,
       -2.49716e-01, -4.21500e-03,  1.11350e-01, -2.42830e-02,
       -3.94520e-02, -6.49660e-02, -1.76680e-01, -1.18322e-01,
       -6.19290e-02,  1.02896e-01, -1.04870e-01, -1.89652e-01,
        5.50480e-02, -2.96387e-01,  6.47680e-02, -8.37700e-02,
       -3.55800e-01,  7.02300e-02,  4.28880e-02, -6.12140e-02,
        1.18126e-01,  3.37119e-01, -2.49170e-02, -4.82070e-02,
        8.26140e-02, -6.36990e-02,  2.24728e-01,  2.95293e-01,
        9.75270e-02,  5.14034e-01, -4.19231e-01,  6.84220e-02,
       -7.21400e-02,  1.29313e-01,  7.03060e-02, -8.16520e-02,
        7.12250e-02,  1.46544e-01,  3.92140e-01, -6.48500e-02,
        1.31805e-01, -1.22907e-01, -4.21550e-02, -7.90560e-02,
       -3.26300e-03,  3.20067e-01,  4.94150e-02,  2.00530e-02,
        5.06698e-01, -2.95075e-01,  1.09822e-01,  1.31554e-01,
       -2.43320e-02,  4.38700e-02, -2.47354e-01,  1.92170e-02,
        1.73002e-01, -2.53870e-01, -2.68560e-01,  1.14819e-01,
        9.70150e-02,  2.84500e-02, -2.80650e-02,  1.27728e-01,
       -1.85379e-01,  6.18710e-02,  1.50343e-01, -1.50460e-01,
       -1.07767e-01, -2.21104e-01,  3.88848e-01, -9.12720e-02,
        1.96515e-01, -2.30470e-01,  1.61700e-03,  7.15770e-02,
        1.25782e-01,  1.43020e-02,  2.97400e-02,  9.27890e-02,
       -1.38105e-01,  1.65060e-01,  1.82653e-01, -9.78160e-02,
       -1.48497e-01, -1.90776e-01,  8.29300e-03,  2.78639e-01,
       -2.66950e-02, -3.58238e-01, -5.68250e-02, -1.77761e-01,
        1.23960e-01, -3.55031e-01,  6.75030e-02, -3.28600e-03,
        1.12200e-02,  9.34700e-03, -2.81682e-01,  5.41800e-03,
       -1.87631e-01, -1.13087e-01,  3.37484e-01,  2.01151e-01,
        1.52452e-01,  4.05700e-02, -1.40966e-01,  1.90493e-01,
        1.25791e-01,  1.77584e-01, -2.36651e-01,  3.65219e-01,
       -5.31220e-02, -3.36370e-02,  2.69680e-02, -7.11240e-02,
       -1.68035e-01,  6.70580e-02, -2.68015e-01, -1.74689e-01,
       -1.90007e-01, -5.41000e-03,  2.50745e-01,  1.64666e-01,
        8.93870e-02, -3.14720e-02, -3.17441e-01, -1.75820e-01,
        8.96710e-02, -6.72230e-02,  6.60468e-01,  2.94310e-02,
        1.45475e-01, -2.62680e-02,  7.48820e-02, -1.24160e-02,
        3.06317e-01, -9.61490e-02,  1.03646e-01,  1.52200e-03,
       -3.25880e-02, -1.11230e-02,  5.01670e-02, -6.20770e-02,
       -5.23490e-02, -2.87081e-01,  3.15965e-01,  1.84826e-01,
        1.08724e-01, -1.30175e-01, -1.87558e-01,  6.64380e-02,
       -2.16192e-01,  1.60442e-01, -2.16076e-01,  5.36510e-02,
       -5.57360e-02, -1.01111e-01, -1.75296e-01,  8.28340e-02,
       -9.67980e-02, -5.53727e-01,  5.21640e-02,  6.81324e-01,
       -1.80604e-01,  4.62000e-04,  2.30140e-02,  1.42932e-01,
       -5.87970e-02,  6.78200e-03,  1.49383e-01,  1.34158e-01,
        2.13117e-01, -1.32714e-01,  6.84730e-02, -1.57571e-01,
        5.10634e-01, -1.57759e-01,  8.94178e-01, -1.95372e-01,
       -8.80320e-02, -1.30054e-01, -7.53680e-02, -1.12915e-01,
        2.22792e-01,  5.04600e-03,  1.79160e-01, -2.49088e-01,
       -1.50652e-01, -4.52212e-01, -2.77070e-02, -2.38308e-01,
       -2.09350e-01,  6.15700e-03,  2.23597e-01,  3.74848e-01,
        1.62327e-01, -1.28241e-01,  3.01968e-01,  9.72470e-02,
        3.27337e-01,  2.36425e-01, -6.88370e-02, -1.43686e-01,
        2.67170e-02, -2.24561e-01,  1.00555e-01,  8.25800e-02,
        3.57127e-01, -2.62359e-01, -2.24028e-01, -1.67673e-01,
       -6.14500e-02, -8.73540e-02,  4.26320e-02,  3.78270e-02,
       -1.23672e-01, -2.71370e-02, -1.20870e-02, -1.08677e-01,
        6.87780e-02,  3.35411e-01,  1.57837e-01,  5.69800e-03,
       -3.46160e-02, -1.48425e-01, -1.93510e-01, -1.53938e-01,
        2.93451e-01,  7.03500e-03, -9.18920e-02,  5.68370e-02,
        1.31624e-01,  3.53790e-02,  3.33180e-01,  1.87632e-01,
        3.16671e-01,  4.57870e-02, -7.56550e-02,  9.79270e-02,
        5.38200e-02,  3.61900e-03,  1.39347e-01,  6.83980e-02,
        2.09200e-02,  3.24995e-01,  2.35175e-01, -2.20395e-01,
       -1.11706e-01, -1.68381e-01, -9.14290e-02, -2.83844e-01,
       -2.01599e-01,  3.35053e-01,  7.03720e-02, -9.89190e-02,
        4.13344e-01,  8.60000e-02,  3.29520e-02,  1.97378e-01,
       -1.37296e-01, -3.49510e-02,  3.16450e-02,  2.54847e-01,
        5.40908e-01,  1.92407e-01,  9.23300e-02,  2.86982e-01,
        9.16800e-03, -1.05762e-01, -1.41812e-01, -1.70514e-01,
       -1.00144e-01, -2.41706e-01,  1.75843e-01,  1.67683e-01,
        6.39050e-02,  1.65622e-01,  1.04160e-02,  1.68689e-01],
      dtype=float32)]